# Generated by Django 4.1 on 2022-10-19 05:09

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_userotp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_college',
            field=models.CharField(default='Add college', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_designation',
            field=models.CharField(default='Add Designation', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_experience',
            field=models.CharField(default='Add working experience', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_location',
            field=models.CharField(default='Add location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_resume',
            field=models.FileField(null=True, upload_to=user.models.upload_resume_to),
        ),
    ]
