# Generated by Django 4.1 on 2022-10-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_profile_profile_college_profile_profile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_mobile_no',
            field=models.CharField(default='Add Mobile Number', max_length=250, null=True),
        ),
    ]
