# Generated by Django 4.1 on 2022-10-26 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0002_rename_content_website_website_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='website_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_indexed', to=settings.AUTH_USER_MODEL),
        ),
    ]
